version: '3.8'

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: studentdb
      MYSQL_USER: vaishnavi
      MYSQL_PASSWORD: Aditya@1234
    ports:
      - "3307:3306"
    networks:
      - student_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  crud-app:
    build: .
    container_name: crud-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: vaishnavi
      SPRING_DATASOURCE_PASSWORD: Aditya@1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - student_network
    restart: on-failure

networks:
  student_network:
    driver: bridge