services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "Aditya@1234"
      MYSQL_DATABASE: studentdb
      MYSQL_USER: vaishnavi
      MYSQL_PASSWORD: "Aditya@1234"
    # Added Volume to save data on your local machine
    volumes:
      - mysql_student_data:/var/lib/mysql
    networks:
      - student_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "vaishnavi", "-pAditya@1234"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  crud-app:
    build: .
    container_name: crud-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: vaishnavi
      SPRING_DATASOURCE_PASSWORD: "Aditya@1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - student_network
    restart: on-failure:5

networks:
  student_network:
    driver: bridge

# Define the volume here
volumes:
  mysql_student_data:
