services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Aditya@1234
      MYSQL_DATABASE: studentdb
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uvaishnavi", "-pAditya@1234"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - student_network

  app:
    image: sivavaishnavi/crud-app:latest
    container_name: crud-app
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/studentdb
      SPRING_DATASOURCE_USERNAME: vaishnavi
      SPRING_DATASOURCE_PASSWORD: Aditya@1234
    restart: on-failure
    networks:
      - student_network

networks:
  student_network:
    driver: bridge